title: 'whatever'
description: "..."
baseurl: "/"
url: "https://faultroll.github.io/whatever"

header_pages:
  - index.md

style: dark

# Build settings
markdown: 
remote_theme: b2a3e8/jekyll-theme-console

